global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - alerts.yml
scrape_configs:
  - job_name: minotaur
    metrics_path: /metrics
    scrape_timeout: 2s
    static_configs:
      - targets: ["127.0.0.1:9090"]
